### ISSUE TITLE
CursorManager

### ISSUE THREAD

**Issue by mphkz** [Webysther/as3rpclib#4]
Hi,

I'm trying to use your lib, but it require the core.swc just for the CursorManager. Is there a way you could update the sources for the lastest apache flex sdk?

Kind regards

**Comment by Webysther** [comment]
Apache Flex is migrating to FlexJS, I'm going to change the readme to tell you the details and recommendations for the migration.

I do not know what is the need to use ActionScript yet, probably to support legacy systems.

But you can remove the CursorManager. For the project and make the change in code, use the details in build.xml to compile it.

Regards,

Webs
